import type { AppData } from './types';
const scope='https://www.googleapis.com/auth/drive.file'; type TokenClient={requestAccessToken:(o?:{prompt?:string})=>void};
declare global{interface Window{google?:{accounts:{oauth2:{initTokenClient:(o:{client_id:string;scope:string;callback:(r:{access_token?:string;error?:string})=>void})=>TokenClient}}}}}
let token='';const api=(url:string,init:RequestInit={})=>fetch(url,{...init,headers:{Authorization:`Bearer ${token}`,...init.headers}});
export const DRIVE_ROOT_FOLDER='WebAppsData';
const LEGACY_DRIVE_ROOT_FOLDER='WebAppData';
export function signIn():Promise<void>{const id=import.meta.env.VITE_GOOGLE_CLIENT_ID;if(!id)throw new Error('Google Client IDが未設定です。');return new Promise((resolve,reject)=>{if(!window.google)return reject(new Error('Google Identity Servicesを読み込めません。'));window.google.accounts.oauth2.initTokenClient({client_id:id,scope,callback:r=>{if(r.access_token){token=r.access_token;resolve();}else reject(new Error(r.error||'ログインに失敗しました。'));}}).requestAccessToken({prompt:''});});}
async function find(name:string,parent?:string){const q=[`name='${name}'`,`trashed=false`,parent?`'${parent}' in parents`:null].filter(Boolean).join(' and ');const r=await api(`https://www.googleapis.com/drive/v3/files?q=${encodeURIComponent(q)}&fields=files(id)&spaces=drive`);if(!r.ok)throw Error('Driveの検索に失敗しました。');return(await r.json()).files?.[0] as {id:string}|undefined;}
async function folder(name:string,parent?:string){const old=await find(name,parent);if(old)return old.id;const r=await api('https://www.googleapis.com/drive/v3/files',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,mimeType:'application/vnd.google-apps.folder',parents:parent?[parent]:undefined})});return(await r.json()).id;}
async function readCloudFrom(rootName:string):Promise<{id?:string,data?:AppData}>{const a=await find(rootName);if(!a)return{};const b=await find('MatrixPartsList',a.id);if(!b)return{};const f=await find('MatrixPartsList-latest.json',b.id);if(!f)return{};const r=await api(`https://www.googleapis.com/drive/v3/files/${f.id}?alt=media`);return{id:f.id,data:await r.json()};}
export async function readCloud():Promise<{id?:string,data?:AppData}>{const current=await readCloudFrom(DRIVE_ROOT_FOLDER);if(current.data)return current;const legacy=await readCloudFrom(LEGACY_DRIVE_ROOT_FOLDER);return legacy.data?{data:legacy.data}:{};}
export async function writeCloud(data:AppData,id?:string):Promise<string>{const a=await folder(DRIVE_ROOT_FOLDER),b=await folder('MatrixPartsList',a);const meta={name:'MatrixPartsList-latest.json',mimeType:'application/json',parents:id?undefined:[b]},bd='matrixBoundary',body=`--${bd}\r\nContent-Type: application/json\r\n\r\n${JSON.stringify(meta)}\r\n--${bd}\r\nContent-Type: application/json\r\n\r\n${JSON.stringify(data)}\r\n--${bd}--`;const r=await api(id?`https://www.googleapis.com/upload/drive/v3/files/${id}?uploadType=multipart`:'https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart',{method:id?'PATCH':'POST',headers:{'Content-Type':`multipart/related; boundary=${bd}`},body});if(!r.ok)throw Error('Driveへの保存に失敗しました。');const saved=await r.json() as {id?:string};return saved.id||id||'';}
